version: '1.0'
services:
  database:
    container_name: database
    build: ./database
    expose:
    - "3306"
    ports:
      - "3306:3306"
    links:
      - backend
      - phpmyadmin
      - frontend
    environment:
      TZ: Europe/Madrid
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DomoServer
      MYSQL_SA_PASSWORD: root
    volumes:
      - database_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      TZ: Europe/Madrid
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
    restart: always

  mqtt:
    container_name: mqtt
    image: toke/mosquitto
    environment:
      TZ: Europe/Madrid
    expose:
      - "1883"
    ports:
      - "1883:1883"
    #network_mode: bridge
    links:
      - backend
    restart: unless-stopped
  
  backend:
    container_name: backend
    build: ./backend
    environment:
      TZ: Europe/Madrid
      MQTT_CONTAINER_NAME: mqtt
      DB_CONTAINER_NAME: database
      FTP_PUBLICHOST: pure-ftpd
      FTP_USER_NAME: DomoUser
      FTP_USER_PASS: DomoPass
    expose:
      - "8000" #FastAIP port
    ports:
      - "8000:80" #FastAIP port
    links:
      - frontend
    restart: always

  frontend:
    container_name: frontend
    build: ./frontend
    environment:
      TZ: Europe/Madrid
      DB_HOSTNAME: database
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: DomoServer
      EXTERNAL_IP: 192.168.1.155
      PMA_PORT: 8081
      API_BACKEND_PORT: 8000
    expose:
      - "80" #HTTP port
      - "443" #HTTPS port
    ports:
      - "80:80" #HTTP port
      - "443:443" #HTTPS port
    restart: always

  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "/folder_on_disk/data:/home/username/"
      - "/folder_on_disk/passwd:/etc/pure-ftpd/passwd"
# uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
#      - "/folder_on_disk/ssl:/etc/ssl/private/"
# or ssl/tls with Let's Encrypt (cert and key as two files)
#      - "/etc/letsencrypt/live/<your_server>/cert.pem:/etc/ssl/private/pure-ftpd-cert.pem"
#      - "/etc/letsencrypt/live/<your_server>/privkey.pem:/etc/ssl/private/pure-ftpd-key.pem"
    environment:
      PUBLICHOST: localhost
      FTP_USER_NAME: DomoUser
      FTP_USER_PASS: DomoPass
      FTP_USER_HOME: /home/username
# also for ssl/tls:
#      ADDED_FLAGS: "--tls=2"
    restart: always

volumes:
  database_data: