version: '1.0'
services:
  database:
    container_name: database
    build: ./database
    expose:
    - "3306"
    ports:
      - "3306:3306"
    links:
      - backend
      - phpmyadmin
      - frontend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DomoServer
      MYSQL_SA_PASSWORD: root
    volumes:
      - database_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  mqtt:
    container_name: mqtt
    image: toke/mosquitto
    expose:
      - "1883"
    ports:
      - "1883:1883"
    #network_mode: bridge
    restart: unless-stopped
    links:
      - backend
  
  backend:
    container_name: backend
    build: ./backend
    environment:
      MQTT_CONTAINER_NAME: mqtt
      DB_CONTAINER_NAME: database
    expose:
      - "3307"
    ports:
      - "3307:3307"

  frontend:
    container_name: frontend
    build: ./frontend
    environment:
      DB_HOSTNAME: database
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: DomoServer
      EXTERNAL_IP: 192.168.1.155
      PMA_PORT: 8081
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"


volumes:
  database_data: