FROM mysql:latest

WORKDIR /database/

COPY . .

#RUN setup.sh
#building command: docker build -t domoserver-database:latest ./database
#container creation:  docker create --network DomoServer_network --name DomoServer-database domoserver-database:latest 